name: SentinelPR

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  sentinel-audit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache Sentinel State
        uses: actions/cache@v4 # Use the latest v4
        with:
          path: |
            .sentinel/db
            .sentinel/hashes.json
          # This key stays the same for every run on this branch
          key: sentinelpr-${{ runner.os }}-${{ github.ref_name }}-${{ hashFiles('src/**') }}
          # If the exact key isn't found, grab the most recent one from this branch
          restore-keys: |
            sentinelpr-${{ runner.os }}-${{ github.ref_name }}-
            sentinelpr-${{ runner.os }}-main-

      - name: Generate Diff File
        # This creates the 'pr.diff' file that your Python script expects
        run: git diff origin/${{ github.base_ref }}...HEAD > pr.diff

      - name: Run SentinelPR Action
        # Points to the current repo (the dot) where action.yml lives
        uses: ./ 
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gemini_api_key: ${{ secrets.GEMINI_API_KEY }}